export const CRAZY_OCTAGON_READER_ABI = [
    // Read Functions
    {
        inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
        name: 'getNFTSummary',
        outputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'bool', name: 'exists', type: 'bool' },
            { internalType: 'bool', name: 'activated', type: 'bool' },
            { internalType: 'uint8', name: 'rarity', type: 'uint8' },
            { internalType: 'uint8', name: 'stars', type: 'uint8' },
            { internalType: 'uint8', name: 'bonusStars', type: 'uint8' },
            { internalType: 'bool', name: 'inGraveyard', type: 'bool' },
            { internalType: 'uint48', name: 'lastPingTime', type: 'uint48' },
            { internalType: 'uint48', name: 'lastBreedTime', type: 'uint48' },
            { internalType: 'uint256', name: 'lockedOcta', type: 'uint256' },
            { internalType: 'int16', name: 'dynBonusBps', type: 'int16' },
            { internalType: 'int16', name: 'specBps', type: 'int16' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getGlobalStats',
        outputs: [
            { internalType: 'uint256', name: 'totalLocked', type: 'uint256' },
            { internalType: 'uint256', name: 'monthlyPool', type: 'uint256' },
            { internalType: 'uint256', name: 'claimReserve', type: 'uint256' },
            { internalType: 'uint256', name: 'sharePerPing_', type: 'uint256' },
            { internalType: 'uint16', name: 'safetyBps_', type: 'uint16' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getBreedQuote',
        outputs: [
            { internalType: 'uint256', name: 'octaCost', type: 'uint256' },
            { internalType: 'uint256', name: 'craaCost', type: 'uint256' },
            { internalType: 'uint256', name: 'lpFromOcta', type: 'uint256' },
            { internalType: 'uint256', name: 'octaToMain', type: 'uint256' },
            { internalType: 'uint256', name: 'sponsorFee', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
            { internalType: 'address', name: 'user', type: 'address' },
        ],
        name: 'getBurnInfo',
        outputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'uint256', name: 'totalAmount', type: 'uint256' },
            { internalType: 'uint256', name: 'claimAt', type: 'uint256' },
            { internalType: 'uint256', name: 'graveReleaseAt', type: 'uint256' },
            { internalType: 'bool', name: 'claimed', type: 'bool' },
            { internalType: 'uint32', name: 'waitMinutes', type: 'uint32' },
            { internalType: 'uint256', name: 'playerAmount', type: 'uint256' },
            { internalType: 'uint256', name: 'poolAmount', type: 'uint256' },
            { internalType: 'uint256', name: 'burnedAmount', type: 'uint256' },
            { internalType: 'uint256', name: 'lpAmount', type: 'uint256' },
            { internalType: 'address', name: 'lpPair', type: 'address' },
            { internalType: 'uint256', name: 'nonce', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getFloorPrice',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getCRAARate',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getPingTiming',
        outputs: [
            { internalType: 'uint256', name: 'pingInterval_', type: 'uint256' },
            { internalType: 'uint256', name: 'maxAccumulation_', type: 'uint256' },
            { internalType: 'uint256', name: 'sweepInterval_', type: 'uint256' },
            { internalType: 'uint256', name: 'monthDuration_', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;
